
CREATE TABLE Wymiar_Czas (
    ID_Czasu INT IDENTITY(1,1) PRIMARY KEY,
    Data DATE UNIQUE,
    Dzien INT,
    Miesiac INT,
    Rok INT
);

CREATE TABLE Wymiar_Komitet_Wyborczy (
    ID_Komitetu INT IDENTITY(1,1) PRIMARY KEY,
    Nazwa VARCHAR(255) UNIQUE,
    Wyniki_2015 INTEGER DEFAULT 0,
    Wyniki_2019 INTEGER DEFAULT 0,
    Wyniki_2023 INTEGER DEFAULT 0
);

CREATE TABLE Wymiar_Obwody_2015 (
    ID_KOMISJI INTEGER PRIMARY KEY,
    KOD_TERYTORIALNY SMALLINT,
    Gmina VARCHAR(350),
    Numer_obwodu SMALLINT,
    Numer_okregu_do_Sejmu SMALLINT,
    Numer_okregu_do_Senatu SMALLINT,
    Mieszkancy SMALLINT,
    Wyborcy SMALLINT,
    Siedziba VARCHAR(350),
    Ulica VARCHAR(350),
    Numer_posesji VARCHAR(255),
    Numer_lokalu VARCHAR(255),
    Miejscowosc VARCHAR(350),
    Kod_pocztowy VARCHAR(20),
    Poczta VARCHAR(100),
    Przystosowany_dla_niepelnosprawnych VARCHAR(3),
    Typ_obszaru VARCHAR(350),
    Typ_obwodu VARCHAR(350),
    Data DATE
);

CREATE TABLE Wymiar_Obwody_2019 (
    ID_KOMISJI INTEGER PRIMARY KEY,
    KOD_TERYTORIALNY SMALLINT,
    Gmina VARCHAR(350),
    Numer_obwodu SMALLINT,
    Numer_okregu_do_Sejmu SMALLINT,
    Numer_okregu_do_Senatu SMALLINT,
    Mieszkancy SMALLINT,
    Wyborcy SMALLINT,
    Siedziba VARCHAR(350),
    Ulica VARCHAR(350),
    Numer_posesji VARCHAR(255),
    Numer_lokalu VARCHAR(255),
    Miejscowosc VARCHAR(350),
    Kod_pocztowy VARCHAR(20),
    Poczta VARCHAR(100),
    Przystosowany_dla_niepelnosprawnych VARCHAR(3),
    Typ_obszaru VARCHAR(350),
    Typ_obwodu VARCHAR(350),
    Data DATE
);

CREATE TABLE Wymiar_Obwody_2023 (
    ID_KOMISJI INTEGER PRIMARY KEY,
    KOD_TERYTORIALNY SMALLINT,
    Gmina VARCHAR(350),
    Numer_obwodu SMALLINT,
    Numer_okregu_do_Sejmu SMALLINT,
    Numer_okregu_do_Senatu SMALLINT,
    Mieszkancy SMALLINT,
    Wyborcy SMALLINT,
    Siedziba VARCHAR(350),
    Ulica VARCHAR(350),
    Numer_posesji VARCHAR(255),
    Numer_lokalu VARCHAR(255),
    Miejscowosc VARCHAR(350),
    Kod_pocztowy VARCHAR(20),
    Poczta VARCHAR(100),
    Przystosowany_dla_niepelnosprawnych VARCHAR(3),
    Typ_obszaru VARCHAR(350),
    Typ_obwodu VARCHAR(350),
    Data DATE
);

CREATE TABLE Fakt_Wyniki_2015 (
    ID_KOMISJI INTEGER PRIMARY KEY,
    Numer_Okregu_Sejm INTEGER,
    Kod_Terytorialny INTEGER,
    Numer_Obwodu INTEGER,
    Gmina VARCHAR(350),
    Liczba_Wyborcow INTEGER,
    Komisja_Otrzymala_Karty INTEGER,
    Niewykorzystane_Karty INTEGER,
    Wydane_Karty INTEGER,
    Liczba_Wyborcow_Pelnomocnik INTEGER,
    Liczba_Wyborcow_Zaswiadczenie INTEGER,
    Liczba_Otrzymanych_Kopert INTEGER,
    Koperty_Brak_Oswiadczenia INTEGER,
    Koperty_Brak_Podpisu INTEGER,
    Koperty_Brak_Karty INTEGER,
    Niezaklejona_Koperta INTEGER,
    Koperty_Do_Urny INTEGER,
    Karty_Z_Urny INTEGER,
    Karty_Z_Kopert INTEGER,
    Karty_Niewazne INTEGER,
    Karty_Wazne INTEGER,
    Glosy_Niewazne INTEGER,
    Glosy_X_Wielu_Kandydatow INTEGER,
    Glosy_Brak_X INTEGER,
    Glosy_X_Uniewazniona_Lista INTEGER,
    Glosy_Wazne INTEGER,
    KW_PIS INTEGER,
    KW_KOALICJA_OBYWATELSKA INTEGER,
    KW_Razem INTEGER,
    KW_Korwin INTEGER,
    KW_PSL INTEGER,
    KW_Zjednoczona_Lewica INTEGER,
    KW_Kukiz INTEGER,
    KW_Nowoczesna INTEGER,
    KW_JOW INTEGER,
    KW_Stonoga INTEGER,
    KW_Ruch_Spoleczny INTEGER,
    KW_Zjednoczeni_Slask INTEGER,
    KW_Samoobrona INTEGER,
    KW_Braun_Szczesc_Boze INTEGER,
    KW_Kongres_Prawicy INTEGER,
    KW_Mniejszosc_Niemiecka INTEGER,
    KW_Obywatele_Do_Parlamentu INTEGER,
    Data DATE,
    FOREIGN KEY (ID_KOMISJI) REFERENCES Wymiar_Obwody_2015(ID_KOMISJI)
);

CREATE TABLE Fakt_Wyniki_2019 (
    ID_KOMISJI INTEGER PRIMARY KEY,
    Kod_Terytorialny INTEGER,
    Numer_Okregu_Sejm INTEGER,
    Numer_Obwodu INTEGER,
    Gmina VARCHAR(350),
    Komisja_Otrzymala_Karty INTEGER,
    Liczba_Wyborcow INTEGER,
    Niewykorzystane_Karty INTEGER,
    Wydane_Karty INTEGER,
    Liczba_Wyborcow_Pelnomocnik INTEGER,
    Liczba_Wyborcow_Zaswiadczenie INTEGER,
    Liczba_Otrzymanych_Kopert INTEGER,
    Koperty_Brak_Oswiadczenia INTEGER,
    Koperty_Brak_Podpisu INTEGER,
    Koperty_Brak_Karty INTEGER,
    Niezaklejona_Koperta INTEGER,
    Koperty_Do_Urny INTEGER,
    Karty_Z_Urny INTEGER,
    Karty_Z_Kopert INTEGER,
    Karty_Niewazne INTEGER,
    Karty_Wazne INTEGER,
    Glosy_Niewazne INTEGER,
    Glosy_X_Wielu_Kandydatow INTEGER,
    Glosy_Brak_X INTEGER,
    Glosy_X_Uniewazniona_Lista INTEGER,
    Glosy_Wazne INTEGER,
    KW_KOALICJA_OBYWATELSKA INTEGER,
    KW_AKCJA_EMERYTOW_RENCISTOW INTEGER,
    KW_KONFEDERACJA INTEGER,
    KW_PSL INTEGER,
    KW_PRAWICA INTEGER,
    KW_PIS INTEGER,
    KW_SKUTECZNI_LIROY INTEGER,
    KW_SLD INTEGER,
    KW_BEZPARTYJNI_SAMORZADOWCY INTEGER,
    KW_OBYWATELE_DO_PARLAMENTU INTEGER,
    Data DATE,
    FOREIGN KEY (ID_KOMISJI) REFERENCES Wymiar_Obwody_2019(ID_KOMISJI)
);

CREATE TABLE Fakt_Wyniki_2023 (
    ID_KOMISJI INTEGER PRIMARY KEY,
    Numer_Obwodu INTEGER,
    Kod_Terytorialny INTEGER,
    Gmina VARCHAR(350),
    Numer_Okregu_Sejm INTEGER,
    Komisja_Otrzymala_Karty INTEGER,
    Liczba_Wyborcow INTEGER,
    Niewykorzystane_Karty INTEGER,
    Wydane_Karty INTEGER,
    Liczba_Wyborcow_Pelnomocnik INTEGER,
    Liczba_Wyborcow_Zaswiadczenie INTEGER,
    Liczba_Otrzymanych_Kopert INTEGER,
    Koperty_Brak_Oswiadczenia INTEGER,
    Koperty_Brak_Podpisu INTEGER,
    Koperty_Brak_Karty INTEGER,
    Niezaklejona_Koperta INTEGER,
    Koperty_Do_Urny INTEGER,
    Karty_Z_Urny INTEGER,
    Karty_Z_Kopert INTEGER,
    Karty_Niewazne INTEGER,
    Karty_Wazne INTEGER,
    Glosy_Niewazne INTEGER,
    Glosy_X_Wielu_Kandydatow INTEGER,
    Glosy_Brak_X INTEGER,
    Glosy_X_Uniewazniona_Lista INTEGER,
    Glosy_Wazne INTEGER,
    KW_Bezpartyjni_Samorzadowcy INTEGER,
    KW_Trzecia_Droga_Polska_2050_PSL INTEGER,
    KW_Nowa_Lewica INTEGER,
    KW_PIS INTEGER,
    KW_Konfederacja INTEGER,
    KW_KOALICJA_OBYWATELSKA INTEGER,
    KW_Polska_Jest_Jedna INTEGER,
    KW_Ruch_Dobrobytu_Pokoju INTEGER,
    KW_Normalny_Kraj INTEGER,
    KW_Antypartia INTEGER,
    KW_Ruch_Naprawy_Polski INTEGER,
    KW_Mniejszosc_Niemiecka INTEGER,
    Data DATE,
    FOREIGN KEY (ID_KOMISJI) REFERENCES Wymiar_Obwody_2023(ID_KOMISJI)
);