ALTER TABLE Fakt_Wyniki_2015 DROP CONSTRAINT IF EXISTS fk_wymiar_obwody_2015;
ALTER TABLE Fakt_Wyniki_2019 DROP CONSTRAINT IF EXISTS fk_wymiar_obwody_2019;
ALTER TABLE Fakt_Wyniki_2023 DROP CONSTRAINT IF EXISTS fk_wymiar_obwody_2023;

ALTER TABLE Agregowane_Wyniki_2015 DROP CONSTRAINT IF EXISTS fk_wymiar_czas_2015;
ALTER TABLE Agregowane_Wyniki_2019 DROP CONSTRAINT IF EXISTS fk_wymiar_czas_2019;
ALTER TABLE Agregowane_Wyniki_2023 DROP CONSTRAINT IF EXISTS fk_wymiar_czas_2023;

DROP TABLE IF EXISTS Wymiar_Obwody_2015;
DROP TABLE IF EXISTS Wymiar_Obwody_2019;
DROP TABLE IF EXISTS Wymiar_Obwody_2023;

DROP TABLE IF EXISTS Fakt_Wyniki_2015;
DROP TABLE IF EXISTS Fakt_Wyniki_2019;
DROP TABLE IF EXISTS Fakt_Wyniki_2023;

DROP TABLE IF EXISTS Agregowane_Wyniki_2015;
DROP TABLE IF EXISTS Agregowane_Wyniki_2019;
DROP TABLE IF EXISTS Agregowane_Wyniki_2023;

DROP TABLE IF EXISTS Wymiar_Czas;
DROP TABLE IF EXISTS Wymiar_Komitet_Wyborczy;