DROP TABLE IF EXISTS Wymiar_Obwody_2015;
DROP TABLE IF EXISTS Wymiar_Obwody_2019;
DROP TABLE IF EXISTS Wymiar_Obwody_2023;

DROP TABLE IF EXISTS Fakt_Wyniki_2015;
DROP TABLE IF EXISTS Fakt_Wyniki_2019;
DROP TABLE IF EXISTS Fakt_Wyniki_2023;